### ISSUE TITLE
[Feature request] Backup all saved recipes

### ISSUE THREAD

**Issue by Philmod** [ianbrault/nyt_recipe#1]
Hi!

I would love to backup all my saved recipes (cooking.nytimes.com/recipe-box). Have you considered building a script for that?

Thanks,
Philmod

**Comment by ianbrault** [comment]
Hi Philmod! 

As far as I can tell, the contents of the recipe box are populated dynamically after the initial page load so I am not aware of an easy way to query this (I tried curl with a cookie file to no success). If you are aware of a way to get this info I would be happy to add it to the script, though.

Best,
Ian
